version: '3.8'

services:
    db:
        container_name: nest-crud-db
        image: mysql:8.0.33
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nest_crud_db
            MYSQL_USER: user_crud
            MYSQL_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3308:3306"

